version: "3.9"
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped

  app:
    image: rust:1.79
    container_name: website-searcher-app
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      - RUST_BACKTRACE=1
      - CF_URL=http://flaresolverr:8191/v1
    depends_on:
      - flaresolverr
    entrypoint: ["bash", "-lc", "cargo build --release && /workspace/target/release/website-searcher"]
