[package.metadata.wix]
# Main product information
product_name = "Website-Searcher"
product_version = "0.1.0"
manufacturer = "reekid420"
upgrade_code = "28B2676A-E142-4B78-A5B9-D71DA624586F"

# Binary configurations
[[package.metadata.wix.binaries]]
name = "website-searcher"
path = "target/release/website-searcher.exe"
description = "Website Searcher CLI Tool"
component_group = "CLI"

[[package.metadata.wix.binaries]]
name = "website-searcher-gui"
path = "target/release/website-searcher-gui.exe"
description = "Website Searcher GUI Application"
component_group = "GUI"

# Feature groups for optional installation
[[package.metadata.wix.features]]
id = "CLI"
title = "Command Line Interface"
description = "Install the CLI tool for command-line usage"
level = "1"
components = ["CLI"]

[[package.metadata.wix.features]]
id = "GUI"
title = "Graphical User Interface"
description = "Install the GUI application"
level = "1"
components = ["GUI"]

# Default features (both selected by default)
[package.metadata.wix.default_features]
CLI = true
GUI = true