name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    name: build-test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest           # x86_64 Linux
          - os: ubuntu-24.04-arm        # arm64 Linux
          - os: macos-13                # x86_64 macOS
          - os: macos-14                # arm64 macOS (Apple Silicon)
          - os: windows-latest          # x86_64 Windows
          - os: windows-11-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.87.0
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: fmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: test
        env:
          RUST_BACKTRACE: 1
          NO_COLOR: 1
        run: cargo test --all --verbose --locked
 
      - name: install audit
        run: cargo install cargo-audit
      
      - name: audit
        run: cargo audit
